# Generated by Django 4.1.1 on 2022-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_created',
            field=models.DateTimeField(),
        ),
    ]
