# Generated by Django 4.1.1 on 2022-12-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_comment_dislike_remove_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_comment', to='news.comment')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.comment')),
            ],
        ),
    ]
