# Generated by Django 4.1.1 on 2023-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_userdislikecomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime_modified',
            field=models.DateTimeField(),
        ),
    ]
