# Generated by Django 4.1.1 on 2023-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_comment_datetime_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('canceled', 'Canceled')], default='pending', max_length=9),
        ),
    ]
