# Generated by Django 4.1.1 on 2023-02-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sport', 'sport'), ('football', 'football'), ('political', 'political'), ('internal', 'internal news'), ('foreign', 'foreign news'), ('exclusive', 'exclusive news')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='news.category')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='news.report')),
            ],
        ),
    ]
