# Generated by Django 4.1.1 on 2023-02-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_category_reportcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'verbose_name_plural': 'Report Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('sport', 'ورزش'), ('football', 'فوتبال'), ('political', 'سیاسی'), ('internal', 'اخبار داخلی'), ('foreign', 'اخبار خارجی'), ('exclusive', 'اخبار اختصاصی')], max_length=20),
        ),
    ]
