# Generated by Django 4.1.1 on 2022-09-11 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('09[0-9]{9}', message='This phone number is incorrect!')]),
        ),
    ]
